### ISSUE TITLE
Add param for all plugins (like a param `allow failures`) for control paths priority when we search plugin binary

### ISSUE THREAD

**Issue by corpsee** [corpsee/php-censor#104]
Add param for all plugins (like a param `allow failures`) for control paths priority when we search plugin binary.

Example:
```yml
test:
  php_unit:
    priority_path: global
    config:
      - phpunit.xml
```

Now default priority:
* Search in local current build path ('local')
* Search in global PHP Censor 'vendor/bin' path ('global')
* Search in system binaries ('system')
