### ISSUE TITLE
TravisCI-like syntax of shell plugin

### ISSUE THREAD

**Issue by ketchoop** [corpsee/php-censor#2]
Current version of this plugin is so inconvenient. Travis-like syntax would be better.

**Comment by corpsee** [comment]
I'll think about it. It would be great if you gave an example of the shell plugin configuration which will better.

**Comment by ket4yii** [comment]
Specifying branches for commands in this plugin is so ugly. Now, you've got to use bash's if expressions(or [  ]) to do something special for branch.

More likely:

```
shell:
  master:
     - echo "Hello, master branch!"
   dev:
      - echo "Hello, dev branch"
   /^experimental-\w+/: # Regex for this would be very convenient, but it's not necessary
      - echo "EXPERIMENTAL"
```

**Comment by corpsee** [comment]
There are global brunch filter. Something like that:
```yml
test:
  shell:
    - echo "Hello, master branch!"
...

branch-dev:
  run-option: replace
    test:
      shell:
        - echo "Hello, dev branch!"
```
It's not what you want?
