### ISSUE TITLE
Custom database port doesn't work

### ISSUE THREAD

**Issue by ket4yii** [corpsee/php-censor#58]
Title is obvious, I think. I tried to solve this problem through the config file and manually. But, it hasn't still worked :(

**Comment by corpsee** [comment]
I will try to debug it tomorrow. Thanks for report.

**Comment by corpsee** [comment]
@ket4yii Can you show your "servers" application config section?

**Comment by ket4yii** [comment]
Here it's

```
b8:
  database:
    servers:
      read:
        - host: db.phpcensor.service.herzen
          port: 3306
      write:
        - host: db.phpcensor.service.herzen
          port: 3306
```

**Comment by corpsee** [comment]
Thanks

**Comment by corpsee** [comment]
For me port doesn't work with 'localhost' host, but works ok with '127.0.0.1' (I don't know how it affect port :smile:).
Quote from [PHP docs](http://php.net/manual/ru/pdo.construct.php):

> I'd like to point out that in PHP 7.0 in the dsn parameter you can't use 'host=localhost' to solve this you can use 'host=127.0.0.1' instead.

In your case host is normal, but who knows...

**Comment by corpsee** [comment]
> Unix only:
> When the host name is set to "localhost", then the connection to the server is made thru a domain socket. If PDO_MYSQL is compiled against libmysql then the location of the socket file is at libmysql's compiled in location. If PDO_MYSQL is compiled against mysqlnd a default socket can be set thru the pdo_mysql.default_socket setting.

**Comment by corpsee** [comment]
May be in your case PHP try to connect by socket instead of TCP?

**Comment by ket4yii** [comment]
Sorry, I sent you wrong config. It's production config and it's ok.

This is another one that I used to connect to:

```
b8:
  database:
    servers:
      read:
        - host: 10.x.x.x
          port: 4306
      write:
        - host: 10.x.x.x
          port: 4306
```

I had a problem with non standard port for mysql.

**Comment by corpsee** [comment]
I think the problem isn't in the application. I try on localhost config:
```yml
b8:
  database:
    servers:
      read:
        - host: 127.0.0.1
          port: 3308
      write:
        - host: 127.0.0.1
          port: 3308
```

And it is work normal if I changed port to 3308 in mysql config...
