### ISSUE TITLE
PHP Coding Standards Fixer : 2 bugs

### ISSUE THREAD

**Issue by vinpel** [corpsee/php-censor#63]
When i follow the documentation i set a level, but got an error :
```yaml
 php_cs_fixer:
    verbose: true
    allow_failures: true
    diff: true
    level: "psr2"
```
give : 
```bash
RUNNING PLUGIN: PHP Coding Standards Fixer (Stage: Test)

                                                          
  [Symfony\Component\Console\Exception\RuntimeException]  
  The "--level" option does not exist.                    
                                                          

Exception trace:
 () at /vendor/symfony/console/Input/ArgvInput.php:219
 Symfony\Component\Console\Input\ArgvInput->addLongOption() at /vendor/symfony/console/Input/ArgvInput.php:153
 Symfony\Component\Console\Input\ArgvInput->parseLongOption() at /vendor/symfony/console/Input/ArgvInput.php:84
 Symfony\Component\Console\Input\ArgvInput->parse() at /vendor/symfony/console/Input/Input.php:63
 Symfony\Component\Console\Input\Input->bind() at /vendor/symfony/console/Command/Command.php:222
 Symfony\Component\Console\Command\Command->run() at /vendor/symfony/console/Application.php:826
 Symfony\Component\Console\Application->doRunCommand() at /vendor/symfony/console/Application.php:189
 Symfony\Component\Console\Application->doRun() at /vendor/symfony/console/Application.php:120
 Symfony\Component\Console\Application->run() at /vendor/friendsofphp/php-cs-fixer/php-cs-fixer:55

fix [--path-mode PATH-MODE] [--allow-risky ALLOW-RISKY] [--config CONFIG] [--dry-run] [--rules RULES] [--using-cache USING-CACHE] [--cache-file CACHE-FILE] [--diff] [--format FORMAT] [--stop-on-violation] [--show-progress SHOW-PROGRESS] [--] [<path>]...


Exception: Warning: chdir(): No such file or directory (errno 2) in /data/htdocs/phpci/src/PHPCensor/Plugin/PhpCsFixer.php line 55
PLUGIN: FAILED (ALLOWED)
```

__Why need to set a workingdir, can we simply use BUILD_PATH and take into account the ignored path ?__

```yaml
 php_cs_fixer:
    verbose: true
    allow_failures: true
    diff: true
    workingdir: "%BUILD_PATH%"
```
give : 
```
RUNNING PLUGIN: PHP Coding Standards Fixer (Stage: Test)
Plugin options: {"verbose":true,"allow_failures":true,"diff":true,"workingdir":"%BUILD_PATH%"}
Exception: Warning: chdir(): No such file or directory (errno 2) in /data/htdocs/phpci/src/PHPCensor/Plugin/PhpCsFixer.php line 48
PLUGIN: FAILED (ALLOWED)
```

**Comment by corpsee** [comment]
Thank you for the bug report @vinpel!

**Comment by corpsee** [comment]
PhpCsFixer have many options and in new versions --level doesn't exist. I refactored plugin and changed options (diff, level etc) to common option `args` for all versions of PhpCsFixer. Examples:

```yml
test:
  php_cs_fixer:
    directory: "./my/dir/path" # == "%BUILD_PATH%/my/dir/path"
    args:      "--rules=@PSR2 --diff --verbose"

test:
  php_cs_fixer:
    directory: "%BUILD_PATH%/my/dir/path"
    args:      "--rules=@PSR2"
```

@vinpel It is ok? Can you test branch `bugfix-63`?

**Comment by corpsee** [comment]
Add more backward compatibility. Examples:
```yml
test:
  php_cs_fixer:
    directory: "./my/dir/path" # == "%BUILD_PATH%/my/dir/path"
    args:      "--rules=@PSR2 --diff --verbose"
```
Or
```yml
test:
  php_cs_fixer:
    directory: "%BUILD_PATH%/my/dir/path"
    verbose:   true
    diff:      true
    rules:     "@PSR2"
```

**Comment by corpsee** [comment]
I tested plugin and close this issue for now, but feel free to reopen.

**Comment by vinpel** [comment]
Thanks for the work.

I retested the modules with a very simple configuration :

```yaml
 php_cs_fixer:
    verbose: true
```
it's my result in log (with debug) 
```bash
RUNNING PLUGIN: PHP Coding Standards Fixer (Stage: Test)
Plugin options: {"verbose":true}
Looking for binary: php-cs-fixer
Found in /vendor/bin: php-cs-fixer
Args: ["\/data\/htdocs\/phpci\/runtime\/builds\/608_c1665\/vendor\/bin\/php-cs-fixer fix . %s"," --verbose"]
Command: /vendor/bin/php-cs-fixer fix .  --verbose
Loaded config default.
.......FFFFFFFFFFFFFFF.FFFF..F.FFFF.FFFFFFFFFFFFFFFFFF.F.FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF.FF..FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF.FFFFFFFFFFFFFF.FF.FFFFF.FFFF.FFFF.FFFFFFFFFFFFFF.........FFF.F...FFFFFFFFF.FF...F..F.F.F.......FFFFF.FFF.F.FFFFFFF............................F.......FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF..FFFFFFFFF.FFF.FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF..FFFF..FIIFFF.FFFFFFFF.FFFFFFFFFFFFFFFFFFFFFFFFFFFF.FFF.FFFFFFFFFFFFF.F.FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF.FFFFFFFFF...F.FFF.FFFFFFFFF.FFFF.F.F..FFF.
Legend: ?-unknown, I-invalid file syntax, file ignored, S-Skipped, .-no changes, F-fixed, E-error

Files that were not fixed due to errors reported during linting before fixing:
```

if i read correcly the plugin change the source file, but didn't inform me of the change and what it's done (like the  todo / readme plugin for exemple) ?

**Comment by corpsee** [comment]
Thank you for testing @vinpel! It is strange... My log (`friendsofphp/php-cs-fixer v2.2.2`, PHP Censor `master` branch):
```bash
RUNNING PLUGIN: PHP Coding Standards Fixer (Stage: Test)
Plugin options: {"verbose":true,"allow_failures":true}
Looking for binary: php-cs-fixer
Found in vendor/bin: php-cs-fixer
Args: ["\/home\/corpsee\/Projects\/php-censor.local\/vendor\/bin\/php-cs-fixer fix . %s"," --verbose"]
Command: /home/corpsee/Projects/php-censor.local/vendor/bin/php-cs-fixer fix .  --verbose
   1) /app/loggerconfig.example.php (function_declaration)
   2) /src/B8Framework/Config.php (no_trailing_whitespace_in_comment, braces)
   3) /src/B8Framework/Form.php (single_import_per_statement)
...
 134) /tests/PHPCensor/Logging/BuildLoggerTest.php (single_blank_line_at_eof)
 135) /tests/PHPCensor/Logging/LoggerConfigTest.php (function_declaration)
 136) /tests/PHPCensor/Command/InstallCommandTest.php (braces)
Fixed all files in 39.076 seconds, 10.000 MB memory used
You are running php-cs-fixer with xdebug enabled. This has a major impact on runtime performance.
Loaded config default.
F.......FFF..F.......F.FF..F..FF....F..FF.....FFFFFF.FFFFF.F...FF.....F...F............F.FFF..FFFFFFFFFF.....F..FFFF..FFFF.F.F...FFFFFFFFFFFFFFFFFFFFFF.FFF.FFFFFFFFFFFFFF......F.FFF.FF.FFF..F.F...........F..FFFF...FF.FFFF..FFFFFFFF....FFFFFFF.F.F.FFF......
Legend: ?-unknown, I-invalid file syntax, file ignored, S-Skipped, .-no changes, F-fixed, E-error

Execution status: 0
PLUGIN: SUCCESS
```

What PHP Censor version (or branch) are you using? PHP version? PhpCsFixer version?

**Comment by corpsee** [comment]
Or you are meaning errors in `error` tab? I didn't understand what is readme plugin?

**Comment by vinpel** [comment]
is use the master branch

PHP_CodeSniffer version 2.8.1 (stable) by Squiz (http://www.squiz.net)
PHP 5.6.30 (cli) (built: Jan 20 2017 01:36:35)


i've retested without options :

![image](https://cloud.githubusercontent.com/assets/1699839/25374759/ee576328-299e-11e7-9829-58525f962900.png)

The comment in the link : the 2 file are normaly ignored in the yaml config file :


my .phpcensor file :
```yaml
build_settings:
    verbose: true
    prefer_symlink: false
    allowed_warnings: 2
    ignore:
      - vendor
      - frontend/tests/_support/_generated
      - frontend/web/assets
      - frontend/runtime/
      - backend/tests/_support/_generated
      - backend/runtime/
      - directory/not/ignored/by/the/plugin
    mysql:
      host: "127.0.0.1"
      user: "root"
      pass: ""
setup:
  mysql:
    - "DROP DATABASE IF EXISTS TEST_DB_BUILD_%BUILD%;"
    - "CREATE DATABASE TEST_DB_BUILD_%BUILD%;"
    - "GRANT ALL PRIVILEGES ON test.* TO test@'localhost' IDENTIFIED BY 'test';"
  composer:
      directory: "."
      action: "install"
      prefer_dist: true
  shell:
#Global Composer
    - "composer global require \"fxp/composer-asset-plugin:^1.2.0\""
# Initialisation de l'application
    - "chmod +x %BUILD_PATH%init && %BUILD_PATH%init --env=Development --overwrite=All"
# Modification de la configuration pour être sur d'avoir une base de donnée vierge
    - "echo TEST_DB_BUILD_%BUILD%"
    - "echo sed -i -e 's,yii2advanced_test,TEST_DB_BUILD_%BUILD%,g' %BUILD_PATH%common/config/test-local.php"
    - "sed -i -e 's,yii2advanced_test,TEST_DB_BUILD_%BUILD%,g' %BUILD_PATH%common/config/test-local.php"
# Migration de la structure des tables
# Deploiement de l'application
    - "chmod +x %BUILD_PATH%yii_test"
    - "chmod +x %BUILD_PATH%scripts/deploy.sh && %BUILD_PATH%scripts/deploy.sh yii_test"
    - "%BUILD_PATH%vendor/bin/codecept build"
test:
  codeception:
    config: codeception.yml
    allow_failures: false
    args: " --steps "
  php_cpd:
    allow_failures: false
  php_loc:
    allow_failures: true
  php_parallel_lint:
  php_docblock_checker:
    allow_failures: true
  technical_debt:
    allow_failures: true
  php_cs_fixer:
    verbose: true
  security_checker:
    allowed_warnings: -1
complete:
  mysql:
    - "DROP DATABASE TEST_DB_BUILD_%BUILD%;"
  email:
    default_mailto_address: email@exemple.to

```

the expected result is entry in the "error"tab :

![image](https://cloud.githubusercontent.com/assets/1699839/25374977/95271f2c-299f-11e7-8de9-93cc1f1ee347.png)

(todo/readme plugin was "technical debt", sorry :p)
