### ISSUE TITLE
PHP Code Sniffer & PHP Copy/Paste Detector Error - SQLSTATE[HY000]: General error 7

### ISSUE THREAD

**Issue by BrunoJunior** [corpsee/php-censor#66]
Error messages :
![image](https://cloud.githubusercontent.com/assets/4368255/26159655/73528be8-3b1f-11e7-89fc-e87bd030a0e9.png)
.php-censor.yml :
```yml
build_settings:
  clone_depth: 1 # depth of 1 is a shallow clone, remove this line to clone entire repo
  ignore:
    - "vendor"
    - "tests"

setup:
  composer:
    action: "install"

test:
  php_mess_detector:
    allow_failures: true
  php_code_sniffer:
    standard: "PSR2"
  php_cpd:
    allow_failures: true
```
