### ISSUE TITLE
Can`t build - status is not pending - After Build error

### ISSUE THREAD

**Issue by BrunoJunior** [corpsee/php-censor#68]
I had some errors in my build.
It's tagged as finished.
But new messages come in build log and I have some running psocesses :
![image](https://cloud.githubusercontent.com/assets/4368255/26196861/9236f26e-3bc0-11e7-831e-b14ed3f00ddb.png)
![image](https://cloud.githubusercontent.com/assets/4368255/26196872/a06bacc6-3bc0-11e7-92f9-a9a20c5830d9.png)
There is my project conf :
![image](https://cloud.githubusercontent.com/assets/4368255/26196921/c3b13296-3bc0-11e7-8594-6befaa165359.png)
And the php-censor yml file :
```
build_settings:
  clone_depth: 1 # depth of 1 is a shallow clone, remove this line to clone entire repo
  ignore:
    - "vendor"

setup:
  composer:
    action: "install"
  shell:
    - "mkdir %BUILD_PATH%/instance"
    - "cp %BUILD_PATH%/build_tools/config_instance.php %BUILD_PATH%/instance/config_instance.php"

test:
  php_parallel_lint:
    ignore:
      - "vendor"
      - "test"
    extensions: php
  php_loc:
    directory: "app"
  php_code_sniffer:
    path: "fwk"
  atoum:
```
