### ISSUE TITLE
PHP CS Fixer ignores "excludes" which defined in .php_cs file

### ISSUE THREAD

**Issue by StudioMaX** [corpsee/php-censor#75]
At this time PHP CS Fixer executes via command like this
`[...]/vendor/bin/php-cs-fixer fix . --some_param`
Defining a dot in this command means that this directory (dot in our case) will overwrite the directories defined in .php_cs file (Details here: https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/2094)

I think we have two solutions to fix this:
1. Just remove path to directory from CLI arguments (`[...]/vendor/bin/php-cs-fixer fix --some_param`).
2. Check that `.php_cs` or `.php_cs.dist` exists at the build directory, and remove path from  CLI arguments if this file exists.

**Comment by corpsee** [comment]
@StudioMaX Thank you for the report! I think your first solution is sensible.

**Comment by corpsee** [comment]
I refactored PhpCsFixer plugin and added option `config`. Now it is working like this (PHP Censor branch `bugfix-issue-75`):
```yml
# Executed command: 
# 1. If exists file .php_cs.dist or .php_cs into the project root: php-cs-fixer fix --verbose --config=./.php_cs[.dist]
# 2. If doesn't exist file .php_cs.dist or .php_cs into the project root: php-cs-fixer . fix --verbose
test:
  php_cs_fixer:
    verbose: true

# Executed command: php-cs-fixer ./src fix
test:
  php_cs_fixer:
    directory: ./src

# Executed command: php-cs-fixer fix --config=./special/dir/.php_cs
test:
  php_cs_fixer:
    config: ./special/dir/.php_cs
```

@StudioMaX Can you check it in your project and say what you think about this solution?
