### ISSUE TITLE
Added regexp support for branch specific stages

### ISSUE THREAD

**Issue by corpsee** [corpsee/php-censor#97]
Added regexp support for branch specific stages.  

See: [configuring_project.md](https://github.com/corpsee/php-censor/blob/master/docs/en/configuring_project.md) and #2.

**Comment by corpsee** [comment]
*TODO*: Add documentation.

**Comment by corpsee** [comment]
Something like that:
```yml
test:
  php_cs_fixer:
    allowed_warnings: -1

branch-regex:^feature\-\d$:
  run-option: replace
  test:
    php_cs_fixer:
      allowed_warnings: 0
```
